// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJbb53N2SZ21OXj35BR_oU6IM_z9kdGsM',
    appId: '1:935344900931:web:d35e90c5436a34c060bdf6',
    messagingSenderId: '935344900931',
    projectId: 'squid-8d19c',
    authDomain: 'squid-8d19c.firebaseapp.com',
    storageBucket: 'squid-8d19c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhc4A9DWMSNpLsl3nq5ZhPoua9wqCNMC4',
    appId: '1:935344900931:android:27a7467f4d9cbca860bdf6',
    messagingSenderId: '935344900931',
    projectId: 'squid-8d19c',
    storageBucket: 'squid-8d19c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrV9ppxIp0CHcG_2DVOqhf-mR9wFa5c3A',
    appId: '1:935344900931:ios:5f61d802407aab2060bdf6',
    messagingSenderId: '935344900931',
    projectId: 'squid-8d19c',
    storageBucket: 'squid-8d19c.appspot.com',
    iosClientId:
        '935344900931-kd9r8r2dj2qs0eshg76gfitblmoqje0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.squid',
  );
}
